// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7F7kfJkyEQNii6YTtLqFS6ePnMPi4rwo',
    appId: '1:164786669034:web:ed3f66a240728fc7f69e93',
    messagingSenderId: '164786669034',
    projectId: 'messaging-app-194f5',
    authDomain: 'messaging-app-194f5.firebaseapp.com',
    storageBucket: 'messaging-app-194f5.appspot.com',
    measurementId: 'G-HGWQ15DCT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaM6rOyJfQbZx-vmQXbMSYYzQmZzdPVAE',
    appId: '1:164786669034:android:f920e2e8c1d4bd06f69e93',
    messagingSenderId: '164786669034',
    projectId: 'messaging-app-194f5',
    storageBucket: 'messaging-app-194f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpEzFEXdV-pgPFlURL9w0E7vqRElg3Pc',
    appId: '1:164786669034:ios:c3a5322231ae5bf2f69e93',
    messagingSenderId: '164786669034',
    projectId: 'messaging-app-194f5',
    storageBucket: 'messaging-app-194f5.appspot.com',
    iosClientId: '164786669034-03v2h201c6g1ebcvn22fbocs37h7enmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );
}
